# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ColumnRelationshipInformation(Model):
    """Column information for relationship.

    :param from_column_name: From Column Name
    :type from_column_name: str
    :param to_column_name: To Column Name
    :type to_column_name: str
    """ 

    _validation = {
        'from_column_name': {'required': True},
        'to_column_name': {'required': True},
    }

    _attribute_map = {
        'from_column_name': {'key': 'FromColumnName', 'type': 'str'},
        'to_column_name': {'key': 'ToColumnName', 'type': 'str'},
    }

    def __init__(self, from_column_name, to_column_name):
        self.from_column_name = from_column_name
        self.to_column_name = to_column_name
