# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .md_entity import MDEntity


class DatabaseEntity(MDEntity):
    """Database entity.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param name: Entity Name.
    :type name: str
    :param type: Possible values include: 'DATABASE', 'TABLE', 'SCHEMA',
     'VIEW', 'FUNCTION', 'PARTITIONINFO', 'RELATIONSHIP'
    :type type: str or :class:`SASEntityType
     <Microsoft.ADF.SyMSAPIClient.models.SASEntityType>`
    :ivar id: Entity Resource Id.
    :vartype id: str
    :param properties:
    :type properties: object
    """

    def __init__(self, name=None, type = None, properties=None):
        super(DatabaseEntity, self).__init__(name=name, type=type, properties=properties)
