# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataSource(Model):
    """Data source properties.

    :param provider: Data source provider information.
    :type provider: str
    :param location: Data source location.
    :type location: str
    :param properties: Property bag.
    :type properties: dict
    """ 

    _validation = {
        'location': {'required': True},
    }

    _attribute_map = {
        'provider': {'key': 'Provider', 'type': 'str'},
        'location': {'key': 'Location', 'type': 'str'},
        'properties': {'key': 'Properties', 'type': '{object}'},
    }

    def __init__(self, location, provider=None, properties=None):
        self.provider = provider
        self.location = location
        self.properties = properties
