# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataColumn(Model):
    """Data column.

    :param name: Column name.
    :type name: str
    :param origin_data_type_name:
    :type origin_data_type_name: :class:`TypeInfo
     <Microsoft.ADF.SyMSAPIClient.models.TypeInfo>`
    """ 

    _validation = {
        'name': {'required': True},
        'origin_data_type_name': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'origin_data_type_name': {'key': 'OriginDataTypeName', 'type': 'TypeInfo'},
    }

    def __init__(self, name, origin_data_type_name):
        self.name = name
        self.origin_data_type_name = origin_data_type_name
