# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DDLPayload(Model):
    """DDL payload.

    :param action_type: Possible values include: 'CREATE', 'ALTER', 'DROP'
    :type action_type: str or :class:`DDLType
     <Microsoft.ADF.SyMSAPIClient.models.DDLType>`
    :param old_entity:
    :type old_entity: :class:`MDEntity
     <Microsoft.ADF.SyMSAPIClient.models.MDEntity>`
    :param new_entity:
    :type new_entity: :class:`MDEntity
     <Microsoft.ADF.SyMSAPIClient.models.MDEntity>`
    """ 

    _validation = {
        'action_type': {'required': True},
    }

    _attribute_map = {
        'action_type': {'key': 'ActionType', 'type': 'DDLType'},
        'old_entity': {'key': 'OldEntity', 'type': 'MDEntity'},
        'new_entity': {'key': 'NewEntity', 'type': 'MDEntity'},
    }

    def __init__(self, action_type, old_entity=None, new_entity=None):
        self.action_type = action_type
        self.old_entity = old_entity
        self.new_entity = new_entity
