# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DistributionInfo(Model):
    """Distribution information.

    :param type: Distribution type.
    :type type: str
    :param keys: Distribution keys.
    :type keys: list of str
    :param count: Distribution count.
    :type count: int
    :param sort_keys: Distribution sort keys.
    :type sort_keys: list of :class:`Sorting
     <Microsoft.ADF.SyMSAPIClient.models.Sorting>`
    """ 

    _attribute_map = {
        'type': {'key': 'Type', 'type': 'str'},
        'keys': {'key': 'Keys', 'type': '[str]'},
        'count': {'key': 'Count', 'type': 'int'},
        'sort_keys': {'key': 'SortKeys', 'type': '[Sorting]'},
    }

    def __init__(self, type=None, keys=None, count=None, sort_keys=None):
        self.type = type
        self.keys = keys
        self.count = count
        self.sort_keys = sort_keys
