# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FormatInfo(Model):
    """Format information.

    :param input_format: Possible values include:
     'org.apache.hadoop.mapred.SequenceFileInputFormat',
     'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
    :type input_format: str
    :param output_format: Possible values include:
     'org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat',
     'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
    :type output_format: str
    :param format_type: Possible values include: 'csv', 'parquet'
    :type format_type: str
    :param properties: Property bag.
    :type properties: dict
    :param ser_de_name: SerDe name.
    :type ser_de_name: str
    :param serialize_lib: Possible values include:
     'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe',
     'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
    :type serialize_lib: str
    """ 

    _validation = {
        'input_format': {'required': True},
        'output_format': {'required': True},
        'format_type': {'required': True},
        'serialize_lib': {'required': True},
    }

    _attribute_map = {
        'input_format': {'key': 'InputFormat', 'type': 'str'},
        'output_format': {'key': 'OutputFormat', 'type': 'str'},
        'format_type': {'key': 'FormatType', 'type': 'str'},
        'properties': {'key': 'Properties', 'type': '{object}'},
        'ser_de_name': {'key': 'SerDeName', 'type': 'str'},
        'serialize_lib': {'key': 'SerializeLib', 'type': 'str'},
    }

    def __init__(self, input_format, output_format, format_type, serialize_lib, properties=None, ser_de_name=None):
        self.input_format = input_format
        self.output_format = output_format
        self.format_type = format_type
        self.properties = properties
        self.ser_de_name = ser_de_name
        self.serialize_lib = serialize_lib
