# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MDEntity(Model):
    """MD Entity.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param name: Entity Name.
    :type name: str
    :param type: Possible values include: 'DATABASE', 'TABLE', 'SCHEMA',
     'VIEW', 'FUNCTION', 'PARTITIONINFO', 'RELATIONSHIP'
    :type type: str or :class:`SASEntityType
     <Microsoft.ADF.SyMSAPIClient.models.SASEntityType>`
    :ivar id: Entity Resource Id.
    :vartype id: str
    :param properties:
    :type properties: object
    """ 

    _validation = {
        'name': {'required': True},
        'type': {'required': True},
        'id': {'readonly': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'SASEntityType'},
        'id': {'key': 'id', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'object'},
    }

    def __init__(self, name, type, properties=None):
        self.name = name
        self.type = type
        self.id = None
        self.properties = properties
