# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Namespace(Model):
    """Namespace.

    :param database_name: Database name.
    :type database_name: str
    """ 

    _validation = {
        'database_name': {'required': True},
    }

    _attribute_map = {
        'database_name': {'key': 'DatabaseName', 'type': 'str'},
    }

    def __init__(self, database_name):
        self.database_name = database_name
