# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .table_namespace import TableNamespace


class PartitionInfoNamespace(TableNamespace):
    """Partition information namespace.

    :param database_name: Database name.
    :type database_name: str
    :param schema_name: Schema name.
    :type schema_name: str
    :param table_name: Table name.
    :type table_name: str
    """ 

    _validation = {
        'database_name': {'required': True},
        'table_name': {'required': True},
    }

    _attribute_map = {
        'database_name': {'key': 'DatabaseName', 'type': 'str'},
        'schema_name': {'key': 'SchemaName', 'type': 'str'},
        'table_name': {'key': 'TableName', 'type': 'str'},
    }

    def __init__(self, database_name, table_name, schema_name=None):
        super(PartitionInfoNamespace, self).__init__(database_name=database_name, schema_name=schema_name)
        self.table_name = table_name
