# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class QueryArtifactsResponse(Model):
    """Query artifacts response.

    :param items:
    :type items: list of object
    :param continuation_token: Continuation token to get next page.
    :type continuation_token: str
    """ 

    _attribute_map = {
        'items': {'key': 'items', 'type': '[object]'},
        'continuation_token': {'key': 'ContinuationToken', 'type': 'str'},
    }

    def __init__(self, items=None, continuation_token=None):
        self.items = items
        self.continuation_token = continuation_token
