# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class StorageDescriptor(Model):
    """Storage descriptor.

    :param distribution: Storage descriptor information.
    :type distribution: :class:`DistributionInfo
     <Microsoft.ADF.SyMSAPIClient.models.DistributionInfo>`
    :param columns: Column information.
    :type columns: list of :class:`DataColumn
     <Microsoft.ADF.SyMSAPIClient.models.DataColumn>`
    :param format: Storage descriptor format information.
    :type format: :class:`FormatInfo
     <Microsoft.ADF.SyMSAPIClient.models.FormatInfo>`
    :param source: Storage descriptor data source information.
    :type source: :class:`DataSource
     <Microsoft.ADF.SyMSAPIClient.models.DataSource>`
    :param properties: Property bag.
    :type properties: dict
    :param ser_de_info: SerDe information.
    :type ser_de_info: object
    """ 

    _validation = {
        'columns': {'required': True},
        'format': {'required': True},
        'source': {'required': True},
    }

    _attribute_map = {
        'distribution': {'key': 'Distribution', 'type': 'DistributionInfo'},
        'columns': {'key': 'Columns', 'type': '[DataColumn]'},
        'format': {'key': 'Format', 'type': 'FormatInfo'},
        'source': {'key': 'Source', 'type': 'DataSource'},
        'properties': {'key': 'Properties', 'type': '{object}'},
        'ser_de_info': {'key': 'SerDeInfo', 'type': 'object'},
    }

    def __init__(self, columns, format, source, distribution=None, properties=None, ser_de_info=None):
        self.distribution = distribution
        self.columns = columns
        self.format = format
        self.source = source
        self.properties = properties
        self.ser_de_info = ser_de_info
