# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SyMSAPIDDLResponses(Model):
    """Defines the publish response.

    :param sy_msapiddl_response: List of DDL response.
    :type sy_msapiddl_response: list of :class:`SyMSAPIDDLResponse
     <Microsoft.ADF.SyMSAPIClient.models.SyMSAPIDDLResponse>`
    """ 

    _validation = {
        'sy_msapiddl_response': {'required': True},
    }

    _attribute_map = {
        'sy_msapiddl_response': {'key': 'SyMSAPIDDLResponse', 'type': '[SyMSAPIDDLResponse]'},
    }

    def __init__(self, sy_msapiddl_response):
        self.sy_msapiddl_response = sy_msapiddl_response
