# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class DDLType(Enum):

    create = "CREATE"
    alter = "ALTER"
    drop = "DROP"


class SASEntityType(Enum):

    database = "DATABASE"
    table = "TABLE"
    schema = "SCHEMA"
    view = "VIEW"
    function = "FUNCTION"
    partitioninfo = "PARTITIONINFO"
    relationship = "RELATIONSHIP"


class InputFormat(Enum):

    orgapachehadoopmapred_sequence_file_input_format = "org.apache.hadoop.mapred.SequenceFileInputFormat"
    orgapachehadoophiveqlioparquet_mapred_parquet_input_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    orgapachehadoopmapred_text_input_format = "org.apache.hadoop.mapred.TextInputFormat"


class OutputFormat(Enum):

    orgapachehadoophiveqlio_hive_sequence_file_output_format = "org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat"
    orgapachehadoophiveqlioparquet_mapred_parquet_output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
    orgapachehadoopmapred_text_output_format = "org.apache.hadoop.mapred.TextOutputFormat"


class FormatType(Enum):

    csv = "csv"
    parquet = "parquet"


class SerializeLib(Enum):

    orgapachehadoophiveserde2lazy_lazy_simple_ser_de = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
    orgapachehadoophiveqlioparquetserde_parquet_hive_ser_de = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"


class SortOrder(Enum):

    desc = "DESC"
    asc = "ASC"


class PublishStatus(Enum):

    published = "PUBLISHED"


class RelationshipType(Enum):

    onetoone = "ONETOONE"
    onetomany = "ONETOMANY"
    manytoone = "MANYTOONE"
    manytomany = "MANYTOMANY"


class TableType(Enum):

    managed = "MANAGED"
    external = "EXTERNAL"


class PartitionFunctionType(Enum):

    value = "value"


class ValidationType(Enum):

    idw_validation = "IDWValidation"


class ValidationStatus(Enum):

    valid = "VALID"
    invalid = "INVALID"
