# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SyMSAPIDDLResponse(Model):
    """Defines the response for create/publish operation on DDL payload.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param ddl_type: Possible values include: 'CREATE', 'ALTER', 'DROP'
    :type ddl_type: str or :class:`DDLType
     <Microsoft.ADF.SyMSAPIClient.models.DDLType>`
    :param entity_name: Entity name.
    :type entity_name: str
    :param entity_type: Possible values include: 'DATABASE', 'TABLE',
     'SCHEMA', 'VIEW', 'FUNCTION', 'PARTITIONINFO', 'RELATIONSHIP'
    :type entity_type: str or :class:`SASEntityType
     <Microsoft.ADF.SyMSAPIClient.models.SASEntityType>`
    :ivar publish_status:  Default value: "PUBLISHED" .
    :vartype publish_status: str
    :param origin_object_id: Object id maintained by Origin Catalog.
    :type origin_object_id: str
    :param object_id: Object id maintained by SyMS.
    :type object_id: str
    :param object_version: Object version maintained by SyMS.
    :type object_version: long
    """ 

    _validation = {
        'ddl_type': {'required': True},
        'entity_name': {'required': True},
        'entity_type': {'required': True},
        'publish_status': {'required': True, 'constant': True},
        'origin_object_id': {'required': True},
        'object_id': {'required': True},
        'object_version': {'required': True},
    }

    _attribute_map = {
        'ddl_type': {'key': 'DDLType', 'type': 'DDLType'},
        'entity_name': {'key': 'EntityName', 'type': 'str'},
        'entity_type': {'key': 'EntityType', 'type': 'SASEntityType'},
        'publish_status': {'key': 'PublishStatus', 'type': 'str'},
        'origin_object_id': {'key': 'OriginObjectId', 'type': 'str'},
        'object_id': {'key': 'ObjectId', 'type': 'str'},
        'object_version': {'key': 'ObjectVersion', 'type': 'long'},
    }

    publish_status = "PUBLISHED"

    def __init__(self, ddl_type, entity_name, entity_type, origin_object_id, object_id, object_version):
        self.ddl_type = ddl_type
        self.entity_name = entity_name
        self.entity_type = entity_type
        self.origin_object_id = origin_object_id
        self.object_id = object_id
        self.object_version = object_version
