# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .namespace import Namespace


class TableNamespace(Namespace):
    """Table namespace.

    :param database_name: Database name.
    :type database_name: str
    :param schema_name: Schema name.
    :type schema_name: str
    """ 

    _validation = {
        'database_name': {'required': True},
    }

    _attribute_map = {
        'database_name': {'key': 'DatabaseName', 'type': 'str'},
        'schema_name': {'key': 'SchemaName', 'type': 'str'},
    }

    def __init__(self, database_name, schema_name=None):
        super(TableNamespace, self).__init__(database_name=database_name)
        self.schema_name = schema_name
