# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TypeInfo(Model):
    """Type information.

    :param type_family: Type family.
    :type type_family: str
    :param type_name: Type name.
    :type type_name: str
    :param is_table_type: Is Table type.
    :type is_table_type: bool
    :param is_complex_type: Is Complex type.
    :type is_complex_type: bool
    :param is_nullable: Is Nullable.
    :type is_nullable: bool
    :param length: Length.
    :type length: int
    :param precision: Precision.
    :type precision: int
    :param scale: Scale.
    :type scale: int
    :param properties: Property bag.
    :type properties: dict
    """ 

    _validation = {
        'type_name': {'required': True},
    }

    _attribute_map = {
        'type_family': {'key': 'TypeFamily', 'type': 'str'},
        'type_name': {'key': 'TypeName', 'type': 'str'},
        'is_table_type': {'key': 'IsTableType', 'type': 'bool'},
        'is_complex_type': {'key': 'IsComplexType', 'type': 'bool'},
        'is_nullable': {'key': 'IsNullable', 'type': 'bool'},
        'length': {'key': 'Length', 'type': 'int'},
        'precision': {'key': 'Precision', 'type': 'int'},
        'scale': {'key': 'Scale', 'type': 'int'},
        'properties': {'key': 'Properties', 'type': '{object}'},
    }

    def __init__(self, type_name, type_family=None, is_table_type=None, is_complex_type=None, is_nullable=None, length=None, precision=None, scale=None, properties=None):
        self.type_family = type_family
        self.type_name = type_name
        self.is_table_type = is_table_type
        self.is_complex_type = is_complex_type
        self.is_nullable = is_nullable
        self.length = length
        self.precision = precision
        self.scale = scale
        self.properties = properties
