# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

from .utils import AutoNumber


class CdmAttributeContextType(AutoNumber):
    ENTITY = ()
    ENTITY_REFERENCE_EXTENDS = ()
    ATTRIBUTE_DEFINITION = ()
    ATTRIBUTE_EXCLUDED = ()
    ATTRIBUTE_GROUP = ()
    GENERATED_SET = ()
    GENERATED_ROUND = ()
    ADDED_ATTRIBUTE_NEW_ARTIFACT = ()
    ADDED_ATTRIBUTE_SUPPORTING = ()
    ADDED_ATTRIBUTE_IDENTITY = ()
    ADDED_ATTRIBUTE_SELECTED_TYPE = ()
    ADDED_ATTRIBUTE_EXPANSION_TOTAL = ()
    PASS_THROUGH = ()
    PROJECTION = ()
    SOURCE = ()
    OPERATIONS = ()
    OPERATION_ADD_COUNT_ATTRIBUTE = ()
    OPERATION_ADD_SUPPORTING_ATTRIBUTE = ()
    OPERATION_ADD_TYPE_ATTRIBUTE = ()
    OPERATION_EXCLUDE_ATTRIBUTES = ()
    OPERATION_ARRAY_EXPANSION = ()
    OPERATION_COMBINE_ATTRIBUTES = ()
    OPERATION_RENAME_ATTRIBUTES = ()
    OPERATION_REPLACE_AS_FOREIGN_KEY = ()
    OPERATION_INCLUDE_ATTRIBUTES = ()
    OPERATION_ADD_ATTRIBUTE_GROUP = ()
    OPERATION_ALTER_TRAITS = ()
    OPERATION_ADD_ARTIFACT_ATTRIBUTE = ()
    UNKNOWN = ()
