//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CommonDataModel.ObjectModel.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CommonDataModel.ObjectModel.Resx.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter not found for the corpus path for namesapce {0}..
        /// </summary>
        internal static string ErrAdapterNotFound {
            get {
                return ResourceManager.GetString("ErrAdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cycle was detected on this definition. An object cannot inherit from itself..
        /// </summary>
        internal static string ErrCycleInObjectDefinition {
            get {
                return ResourceManager.GetString("ErrCycleInObjectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter not found for the document &apos;{0}&apos;.
        /// </summary>
        internal static string ErrDocAdapterNotFound {
            get {
                return ResourceManager.GetString("ErrDocAdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document {0} already exist in folder {1}..
        /// </summary>
        internal static string ErrDocAlreadyExist {
            get {
                return ResourceManager.GetString("ErrDocAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed saving local entity schema document {0}.
        /// </summary>
        internal static string ErrDocEntityDocSavingFailure {
            get {
                return ResourceManager.GetString("ErrDocEntityDocSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to replace source entity&apos;s document &apos;{0}&apos;..
        /// </summary>
        internal static string ErrDocEntityReplacementFailure {
            get {
                return ResourceManager.GetString("ErrDocEntityReplacementFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed saving imported document {0}.
        /// </summary>
        internal static string ErrDocImportSavingFailure {
            get {
                return ResourceManager.GetString("ErrDocImportSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document containing the entity &apos;{0}&apos; is not in a folder.
        /// </summary>
        internal static string ErrDocIsNotFolder {
            get {
                return ResourceManager.GetString("ErrDocIsNotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed saving partition schema document {0}.
        /// </summary>
        internal static string ErrDocPartitionSchemaSavingFailure {
            get {
                return ResourceManager.GetString("ErrDocPartitionSchemaSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed saving sub-manifest document {0}.
        /// </summary>
        internal static string ErrDocSubManifestSavingFailure {
            get {
                return ResourceManager.GetString("ErrDocSubManifestSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find symbol &apos;{0}&apos; in document[{1}].
        /// </summary>
        internal static string ErrDocSymbolNotFound {
            get {
                return ResourceManager.GetString("ErrDocSymbolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No WRT document was supplied..
        /// </summary>
        internal static string ErrDocWrtDocNotfound {
            get {
                return ResourceManager.GetString("ErrDocWrtDocNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected entity to have an &quot;Owner&quot; document set. Cannot create entity declaration to add to manifest..
        /// </summary>
        internal static string ErrEntityCreationFailed {
            get {
                return ResourceManager.GetString("ErrEntityCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert string &apos;{0}&apos; to its corresponding enumeration value for Enum &apos;{1}&apos; on &apos;{2}&apos;..
        /// </summary>
        internal static string ErrEnumConversionFailure {
            get {
                return ResourceManager.GetString("ErrEnumConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch file metadata from root location, the &apos;{0}&apos; adapter may be misconfigured..
        /// </summary>
        internal static string ErrFetchingFileMetadataNull {
            get {
                return ResourceManager.GetString("ErrFetchingFileMetadataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not index document..
        /// </summary>
        internal static string ErrIndexFailed {
            get {
                return ResourceManager.GetString("ErrIndexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object found at path &apos;{0}&apos; cannot be cast to an object of type &apos;{1}&apos;. Please check that the object or the path is specified correctly..
        /// </summary>
        internal static string ErrInvalidCast {
            get {
                return ResourceManager.GetString("ErrInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path &apos;{0}&apos;.
        /// </summary>
        internal static string ErrInvalidPath {
            get {
                return ResourceManager.GetString("ErrInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute last modified time for manifest file {0}. Exception: {1}.
        /// </summary>
        internal static string ErrManifestFileModTimeFailure {
            get {
                return ResourceManager.GetString("ErrManifestFileModTimeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This &apos;{0}&apos; object &apos;{1}&apos; does not contain the trait &apos;{2}&apos;, so it should not be in the collection &apos;{3}&apos;..
        /// </summary>
        internal static string ErrMissingIncrementalPartitionTrait {
            get {
                return ResourceManager.GetString("ErrMissingIncrementalPartitionTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found object without owner when calculating relationships..
        /// </summary>
        internal static string ErrObjectWithoutOwnerFound {
            get {
                return ResourceManager.GetString("ErrObjectWithoutOwnerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get file metadata for partition file {0}. Exception: {1}.
        /// </summary>
        internal static string ErrPartitionFileMetadataFailure {
            get {
                return ResourceManager.GetString("ErrPartitionFileMetadataFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute last modified time for partition file {0}. Exception: {1}.
        /// </summary>
        internal static string ErrPartitionFileModTimeFailure {
            get {
                return ResourceManager.GetString("ErrPartitionFileModTimeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate declaration for item &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPathIsDuplicate {
            get {
                return ResourceManager.GetString("ErrPathIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object path cannot be null or empty..
        /// </summary>
        internal static string ErrPathNullObjectPath {
            get {
                return ResourceManager.GetString("ErrPathNullObjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a storage adapter registered for the namespace &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistAdapterNotFoundForNamespace {
            get {
                return ResourceManager.GetString("ErrPersistAdapterNotFoundForNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage adapter &apos;{0}&apos; reports it is unable to write files..
        /// </summary>
        internal static string ErrPersistAdapterWriteFailure {
            get {
                return ResourceManager.GetString("ErrPersistAdapterWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both minimum and maximum are required for the Cardinality property..
        /// </summary>
        internal static string ErrPersistCardinalityPropMissing {
            get {
                return ResourceManager.GetString("ErrPersistCardinalityPropMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to fetch cdm entity doc..
        /// </summary>
        internal static string ErrPersistCdmEntityFetchError {
            get {
                return ResourceManager.GetString("ErrPersistCdmEntityFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a Persistence class to handle the file &apos;{0}&apos;. Supported formats are model.json, manifest.cdm.json and cdm.json..
        /// </summary>
        internal static string ErrPersistClassMissing {
            get {
                return ResourceManager.GetString("ErrPersistClassMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert &apos;{0}&apos;. Reason &apos;{1}&apos;..
        /// </summary>
        internal static string ErrPersistConversionError {
            get {
                return ResourceManager.GetString("ErrPersistConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while processing csv format settings inside data partition..
        /// </summary>
        internal static string ErrPersistCsvProcessingError {
            get {
                return ResourceManager.GetString("ErrPersistCsvProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize entity declaration. Reason: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPersistDeserializeError {
            get {
                return ResourceManager.GetString("ErrPersistDeserializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading document &apos;{0}&apos;. Reason: {1}.
        /// </summary>
        internal static string ErrPersistDocConversionFailure {
            get {
                return ResourceManager.GetString("ErrPersistDocConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load &apos;{0}&apos;, as it&apos;s not an acceptable file name. File must be named &apos;{1}&apos;..
        /// </summary>
        internal static string ErrPersistDocNameLoadFailure {
            get {
                return ResourceManager.GetString("ErrPersistDocNameLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityAttribute {0} is projection based. Resolution guidance is not supported with a projection..
        /// </summary>
        internal static string ErrPersistEntityAttrUnsupported {
            get {
                return ResourceManager.GetString("ErrPersistEntityAttrUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity declaration type defined for entity &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistEntityDeclarationMissing {
            get {
                return ResourceManager.GetString("ErrPersistEntityDeclarationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity path not set in entity declaration for entity &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistEntityPathNotFound {
            get {
                return ResourceManager.GetString("ErrPersistEntityPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to persist &apos;{0}&apos;, as it&apos;s not an acceptable file name. File must be named &apos;{1}&apos;..
        /// </summary>
        internal static string ErrPersistFailure {
            get {
                return ResourceManager.GetString("ErrPersistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not persist file &apos;{0}&apos;. Reason {1}..
        /// </summary>
        internal static string ErrPersistFilePersistError {
            get {
                return ResourceManager.GetString("ErrPersistFilePersistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to persist &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPersistFilePersistFailed {
            get {
                return ResourceManager.GetString("ErrPersistFilePersistFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read &apos;{0}&apos; from the &apos;{1}&apos; namespace. Reason &apos;{2}&apos;.
        /// </summary>
        internal static string ErrPersistFileReadFailure {
            get {
                return ResourceManager.GetString("ErrPersistFileReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to persist document &apos;{0}&apos;. Reason: {1}..
        /// </summary>
        internal static string ErrPersistFileWriteFailure {
            get {
                return ResourceManager.GetString("ErrPersistFileWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to persist object &apos;{0}&apos;. This object contains the trait &apos;{1}&apos;, so it should not be in the collection &apos;{2}&apos;..
        /// </summary>
        internal static string ErrPersistIncrementalConversionError {
            get {
                return ResourceManager.GetString("ErrPersistIncrementalConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum cardinality {0}. Value must be greater than or equal to 0 and less than maxCardinality..
        /// </summary>
        internal static string ErrPersistInvalidMaxCardinality {
            get {
                return ResourceManager.GetString("ErrPersistInvalidMaxCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum cardinality {0}. Value must be a number greater than zero or &apos;*&apos;..
        /// </summary>
        internal static string ErrPersistInvalidMinCardinality {
            get {
                return ResourceManager.GetString("ErrPersistInvalidMinCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert from JSON to CdmAttributeContext. Reason: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPersistJsonAttrContextConversionError {
            get {
                return ResourceManager.GetString("ErrPersistJsonAttrContextConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert from JSON to CdmDataTypeDefinition. Reason: JSON object is null.
        /// </summary>
        internal static string ErrPersistJsonDatatypeConversionError {
            get {
                return ResourceManager.GetString("ErrPersistJsonDatatypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert from JSON to DataTypeRef. Reason: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPersistJsonDatatypeRefConversionError {
            get {
                return ResourceManager.GetString("ErrPersistJsonDatatypeRefConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert from JSON to CdmImport. Reason: JSON object is null.
        /// </summary>
        internal static string ErrPersistJsonImportConversionError {
            get {
                return ResourceManager.GetString("ErrPersistJsonImportConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to save to file. Reason: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPersistJsonObjectRefConversionError {
            get {
                return ResourceManager.GetString("ErrPersistJsonObjectRefConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Id {0} from {1} not found in referenceModels..
        /// </summary>
        internal static string ErrPersistModelIdNotFound {
            get {
                return ResourceManager.GetString("ErrPersistModelIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to fetch the entity doc from local entity declaration Persistence..
        /// </summary>
        internal static string ErrPersistModelJsonDocConversionError {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonDocConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving a manifest with an entity containing an entity attribute to model.json format is not supported..
        /// </summary>
        internal static string ErrPersistModelJsonEntityAttrError {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonEntityAttrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert a  CDM entity from model.json for entity {0}..
        /// </summary>
        internal static string ErrPersistModelJsonEntityConversionError {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonEntityConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert {0}&apos;s entity declaration to model json format..
        /// </summary>
        internal static string ErrPersistModelJsonEntityDeclarationConversionError {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonEntityDeclarationConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert {0}&apos;s entity declaration to model json format. Exception: {1}.
        /// </summary>
        internal static string ErrPersistModelJsonEntityDeclarationConversionFailure {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonEntityDeclarationConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to parse model.json entity..
        /// </summary>
        internal static string ErrPersistModelJsonEntityParsingError {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonEntityParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert reference entity from model.json for entity {0}..
        /// </summary>
        internal static string ErrPersistModelJsonEntityRefConversionError {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonEntityRefConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert model.json attribute from cdm attribute..
        /// </summary>
        internal static string ErrPersistModelJsonFromAttrConversionFailure {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonFromAttrConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity path set in reference entity &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistModelJsonInvalidEntityPath {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonInvalidEntityPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model.json extension trait name &apos;{0}&apos;, expected prefix &apos;{1}&apos;..
        /// </summary>
        internal static string ErrPersistModelJsonInvalidExtensionTrait {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonInvalidExtensionTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same ModelId &apos;{0}&apos; pointing to different locations..
        /// </summary>
        internal static string ErrPersistModelJsonModelIdDuplication {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonModelIdDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model.json location &apos;{0}&apos; for the entity &apos;{1}&apos; could not be understood by any storage adapter..
        /// </summary>
        internal static string ErrPersistModelJsonRefEntityInvalidLocation {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonRefEntityInvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to convert model.json attribute to cdm attribute..
        /// </summary>
        internal static string ErrPersistModelJsonToAttrConversionFailure {
            get {
                return ResourceManager.GetString("ErrPersistModelJsonToAttrConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to persist object &apos;{0}&apos;. This object does not contain the trait &apos;{1}&apos;, so it should not be in the collection &apos;{2}&apos;..
        /// </summary>
        internal static string ErrPersistNonIncrementalConversionError {
            get {
                return ResourceManager.GetString("ErrPersistNonIncrementalConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name cannot be null or empty..
        /// </summary>
        internal static string ErrPersistNullDocName {
            get {
                return ResourceManager.GetString("ErrPersistNullDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get object from path {0}.
        /// </summary>
        internal static string ErrPersistObjectNotFound {
            get {
                return ResourceManager.GetString("ErrPersistObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation type &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistProjInvalidOpsType {
            get {
                return ResourceManager.GetString("ErrPersistProjInvalidOpsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported: &apos;{0}&apos; property type should be &apos;{1}&apos;..
        /// </summary>
        internal static string ErrPersistProjUnsupportedProp {
            get {
                return ResourceManager.GetString("ErrPersistProjUnsupportedProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save linked documents for file &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistSaveLinkedDocs {
            get {
                return ResourceManager.GetString("ErrPersistSaveLinkedDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location mentioned in dcoument with name {0} is not mounted..
        /// </summary>
        internal static string ErrPersistSymsAdlsAdapterMissing {
            get {
                return ResourceManager.GetString("ErrPersistSymsAdlsAdapterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appropriate adls adapter for path {0} is not mounted. Tried creating new one but failed..
        /// </summary>
        internal static string ErrPersistSymsAdlsAdapterNotMounted {
            get {
                return ResourceManager.GetString("ErrPersistSymsAdlsAdapterNotMounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms to CDM conversion failed for entity {0} because data column was not recieved from syms..
        /// </summary>
        internal static string ErrPersistSymsAttrConversionError {
            get {
                return ResourceManager.GetString("ErrPersistSymsAttrConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms to CDM conversion failed for attribute {0} for entity {1}..
        /// </summary>
        internal static string ErrPersistSymsAttrConversionFailure {
            get {
                return ResourceManager.GetString("ErrPersistSymsAttrConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;is.storagesource&apos; trait is missing in database {0}. This is mandatory trait for syms conversion..
        /// </summary>
        internal static string ErrPersistSymsDBSourceTraitMissing {
            get {
                return ResourceManager.GetString("ErrPersistSymsDBSourceTraitMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms Adapter write operation to create database for document &apos;{0}&apos; failed. Reason &apos;{1}&apos;..
        /// </summary>
        internal static string ErrPersistSymsDbWriteFailed {
            get {
                return ResourceManager.GetString("ErrPersistSymsDbWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms conversion failed for entity &apos;{0}&apos;. Reason &apos;{1}&apos;.
        /// </summary>
        internal static string ErrPersistSymsEntityDeclConversionException {
            get {
                return ResourceManager.GetString("ErrPersistSymsEntityDeclConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms conversion failed for entity &apos;{0}&apos;..
        /// </summary>
        internal static string ErrPersistSymsEntityDeclConversionFailure {
            get {
                return ResourceManager.GetString("ErrPersistSymsEntityDeclConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching CDM entity document from path &apos;{0}&apos;.
        /// </summary>
        internal static string ErrPersistSymsEntityFetchError {
            get {
                return ResourceManager.GetString("ErrPersistSymsEntityFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity path for entity {0} is null..
        /// </summary>
        internal static string ErrPersistSymsEntityPathNull {
            get {
                return ResourceManager.GetString("ErrPersistSymsEntityPathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension {0} is incompatible with file type {1}..
        /// </summary>
        internal static string ErrPersistSymsIncompatibleFileToType {
            get {
                return ResourceManager.GetString("ErrPersistSymsIncompatibleFileToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database object receieved from syms was either null or not with type as DATABASE..
        /// </summary>
        internal static string ErrPersistSymsInvalidDbObject {
            get {
                return ResourceManager.GetString("ErrPersistSymsInvalidDbObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database properties object received from syms either was empty or didn&apos;t have source location..
        /// </summary>
        internal static string ErrPersistSymsInvalidDbPropObject {
            get {
                return ResourceManager.GetString("ErrPersistSymsInvalidDbPropObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cdm entity document {0} either has zero or multiple entity definitions for SyMS table..
        /// </summary>
        internal static string ErrPersistSymsMultipleOrZeroTableDefinition {
            get {
                return ResourceManager.GetString("ErrPersistSymsMultipleOrZeroTableDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables without data partition are not supported in syms..
        /// </summary>
        internal static string ErrPersistSymsNotSupported {
            get {
                return ResourceManager.GetString("ErrPersistSymsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship type &apos;{0}&apos; not supported by SyMS persistence..
        /// </summary>
        internal static string ErrPersistSymsRelationshipTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrPersistSymsRelationshipTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trait must be defined. It must have argument name {1} value in format &apos;&lt;namespace&gt;:/&apos; and mounted to adls apapter..
        /// </summary>
        internal static string ErrPersistSymsStorageSourceTraitError {
            get {
                return ResourceManager.GetString("ErrPersistSymsStorageSourceTraitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unknown format type for table {0}. Supported format types are &apos;CSV&apos; and &apos;parquet&apos;..
        /// </summary>
        internal static string ErrPersistSymsTableFormatTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrPersistSymsTableFormatTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms table {0} data location should either be folder or .csv file..
        /// </summary>
        internal static string ErrPersistSymsTableInvalidDataLocation {
            get {
                return ResourceManager.GetString("ErrPersistSymsTableInvalidDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms table {0} data location is empty..
        /// </summary>
        internal static string ErrPersistSymsTableMissingDataLocation {
            get {
                return ResourceManager.GetString("ErrPersistSymsTableMissingDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get all tables from SyMS for document path &apos;{0}&apos;. Reason: &apos;{1}&apos;.
        /// </summary>
        internal static string ErrPersistSymsTablesReadFailed {
            get {
                return ResourceManager.GetString("ErrPersistSymsTablesReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syms Adapter write operation to create tables for document &apos;{0}&apos; failed. Reason &apos;{1}&apos;. Payload = {2}.
        /// </summary>
        internal static string ErrPersistSymsTableWriteFailed {
            get {
                return ResourceManager.GetString("ErrPersistSymsTableWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unknown CDM data format for attribute {0} which can not be mapped to syMS..
        /// </summary>
        internal static string ErrPersistSymsUnknownDataFormat {
            get {
                return ResourceManager.GetString("ErrPersistSymsUnknownDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; can not be saved in SyMS as it has multiple databases to saved..
        /// </summary>
        internal static string ErrPersistSymsUnsupportedCdmConversion {
            get {
                return ResourceManager.GetString("ErrPersistSymsUnsupportedCdmConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; is not supported for save. Use &lt;databaseName&gt;/&lt;databaseName&gt;.manifest.cdm.json to save SyMS database..
        /// </summary>
        internal static string ErrPersistSymsUnsupportedManifest {
            get {
                return ResourceManager.GetString("ErrPersistSymsUnsupportedManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format type recevied from SyMS. Supported types are &apos;CSV&apos; and &apos;parquet&apos;..
        /// </summary>
        internal static string ErrPersistSymsUnsupportedTableFormat {
            get {
                return ResourceManager.GetString("ErrPersistSymsUnsupportedTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ObjectModel version supports json semantic version {0} at maximum. Trying to load a document with version {1}..
        /// </summary>
        internal static string ErrPersistUnsupportedJsonSemVer {
            get {
                return ResourceManager.GetString("ErrPersistUnsupportedJsonSemVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve a projection. Check previous logs to get more details..
        /// </summary>
        internal static string ErrProjFailedToResolve {
            get {
                return ResourceManager.GetString("ErrProjFailedToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ProjectionAttributeState provided for addition to the Set. Add operation failed..
        /// </summary>
        internal static string ErrProjInvalidAttrState {
            get {
                return ResourceManager.GetString("ErrProjInvalidAttrState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate state for reference attribute \&quot;{0}\&quot;..
        /// </summary>
        internal static string ErrProjRefAttrStateFailure {
            get {
                return ResourceManager.GetString("ErrProjRefAttrStateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameFormat should be set for this operation to work..
        /// </summary>
        internal static string ErrProjRenameFormatIsNotSet {
            get {
                return ResourceManager.GetString("ErrProjRenameFormatIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source can only be another projection in a type attribute..
        /// </summary>
        internal static string ErrProjSourceError {
            get {
                return ResourceManager.GetString("ErrProjSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get number for string &apos;{0}&apos;. Using default value &apos;{1}&apos;..
        /// </summary>
        internal static string ErrProjStringError {
            get {
                return ResourceManager.GetString("ErrProjStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array expansion operation does not support attribute groups..
        /// </summary>
        internal static string ErrProjUnsupportedAttrGroups {
            get {
                return ResourceManager.GetString("ErrProjUnsupportedAttrGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported source type &apos;{0}&apos; in operation &apos;{1}&apos;..
        /// </summary>
        internal static string ErrProjUnsupportedSource {
            get {
                return ResourceManager.GetString("ErrProjUnsupportedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regex calculation timed out..
        /// </summary>
        internal static string ErrRegexTimeout {
            get {
                return ResourceManager.GetString("ErrRegexTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex timeout &apos;{0}&apos; is not valid. Reason &apos;{1}&apos;.
        /// </summary>
        internal static string ErrRegexTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("ErrRegexTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of resolved attributes reached for the entity: {0}..
        /// </summary>
        internal static string ErrRelMaxResolvedAttrReached {
            get {
                return ResourceManager.GetString("ErrRelMaxResolvedAttrReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has the dataType of &apos;{1}&apos; but the value &apos;{2}&apos; doesn&apos;t resolve to a known {3} reference.
        /// </summary>
        internal static string ErrResolutionFailure {
            get {
                return ResourceManager.GetString("ErrResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve entity {0}.
        /// </summary>
        internal static string ErrResolveEntityFailure {
            get {
                return ResourceManager.GetString("ErrResolveEntityFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder not found {0}.
        /// </summary>
        internal static string ErrResolveFolderNotFound {
            get {
                return ResourceManager.GetString("ErrResolveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create resolved manifest &apos;{0}&apos; because a manifest with that name already exists in folder &apos;{1}&apos;.
        /// </summary>
        internal static string ErrResolveManifestExists {
            get {
                return ResourceManager.GetString("ErrResolveManifestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve the manifest &apos;{0}&apos; because it has not been added to a folder.
        /// </summary>
        internal static string ErrResolveManifestFailed {
            get {
                return ResourceManager.GetString("ErrResolveManifestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entity name not provided for resolved entity..
        /// </summary>
        internal static string ErrResolveNewEntityNameNotSet {
            get {
                return ResourceManager.GetString("ErrResolveNewEntityNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve the reference &apos;{0}&apos; to a known object.
        /// </summary>
        internal static string ErrResolveReferenceFailure {
            get {
                return ResourceManager.GetString("ErrResolveReferenceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter not found for the namespace &apos;{0}&apos;.
        /// </summary>
        internal static string ErrStorageAdapterNotFound {
            get {
                return ResourceManager.GetString("ErrStorageAdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find assembly &apos;{0}&apos;, please install the package, and add it as dependency of the project. Exception: {1}..
        /// </summary>
        internal static string ErrStorageCdmStandardsMissing {
            get {
                return ResourceManager.GetString("ErrStorageCdmStandardsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found for the namespace &apos;{0}&apos;.
        /// </summary>
        internal static string ErrStorageFolderNotFound {
            get {
                return ResourceManager.GetString("ErrStorageFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered storage adapter understood the path &apos;{0}&apos;.
        /// </summary>
        internal static string ErrStorageInvalidAdapterPath {
            get {
                return ResourceManager.GetString("ErrStorageInvalidAdapterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path should not start with &apos;./&apos; or &apos;.\&apos;and should not contain &apos;../&apos; , &apos;..\&apos;, &apos;/./&apos;, &apos;\.\&apos;..
        /// </summary>
        internal static string ErrStorageInvalidPathFormat {
            get {
                return ResourceManager.GetString("ErrStorageInvalidPathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing JSON config for the namespace {0}..
        /// </summary>
        internal static string ErrStorageMissingJsonConfig {
            get {
                return ResourceManager.GetString("ErrStorageMissingJsonConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace is missing for one of the adapters..
        /// </summary>
        internal static string ErrStorageMissingNamespace {
            get {
                return ResourceManager.GetString("ErrStorageMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing type in Json config for the namespace {0}..
        /// </summary>
        internal static string ErrStorageMissingTypeJsonConfig {
            get {
                return ResourceManager.GetString("ErrStorageMissingTypeJsonConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace &apos;{0}&apos; found on the path &apos;{1}&apos; does not match the namespace found on the object &apos;{2}&apos; which has namespace &apos;{3}&apos;..
        /// </summary>
        internal static string ErrStorageNamespaceMismatch {
            get {
                return ResourceManager.GetString("ErrStorageNamespaceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace {0} has not been registered.
        /// </summary>
        internal static string ErrStorageNamespaceNotRegistered {
            get {
                return ResourceManager.GetString("ErrStorageNamespaceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter cannot be null..
        /// </summary>
        internal static string ErrStorageNullAdapter {
            get {
                return ResourceManager.GetString("ErrStorageNullAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter config cannot be null or empty..
        /// </summary>
        internal static string ErrStorageNullAdapterConfig {
            get {
                return ResourceManager.GetString("ErrStorageNullAdapterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corpus path is null or empty.
        /// </summary>
        internal static string ErrStorageNullCorpusPath {
            get {
                return ResourceManager.GetString("ErrStorageNullCorpusPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace cannot be null or empty.
        /// </summary>
        internal static string ErrStorageNullNamespace {
            get {
                return ResourceManager.GetString("ErrStorageNullNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config cannot be cast to objectNode. Config: {0}, Error: {1}.
        /// </summary>
        internal static string ErrStorageObjectNodeCastFailed {
            get {
                return ResourceManager.GetString("ErrStorageObjectNodeCastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find symbol &apos;{0}&apos;.
        /// </summary>
        internal static string ErrSymbolNotFound {
            get {
                return ResourceManager.GetString("ErrSymbolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No argument supplied for required parameter &apos;{0}&apos; of trait &apos;{1}&apos; on &apos;{2}&apos;.
        /// </summary>
        internal static string ErrTraitArgumentMissing {
            get {
                return ResourceManager.GetString("ErrTraitArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while trying to get attributes with traits. Reason: {0}.
        /// </summary>
        internal static string ErrTraitAttrFetchError {
            get {
                return ResourceManager.GetString("ErrTraitAttrFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of argument value supplied for the parameter &apos;{0}&apos; of trait &apos;{1}&apos; on &apos;{2}&apos;..
        /// </summary>
        internal static string ErrTraitInvalidArgumentValueType {
            get {
                return ResourceManager.GetString("ErrTraitInvalidArgumentValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve parameter on trait &apos;{0}&apos;. Exception : {1}.
        /// </summary>
        internal static string ErrTraitResolutionFailure {
            get {
                return ResourceManager.GetString("ErrTraitResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter &apos;${0}&apos; has an unexpected dataType..
        /// </summary>
        internal static string ErrUnexpectedDataType {
            get {
                return ResourceManager.GetString("ErrUnexpectedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This &apos;{0}&apos; object &apos;{1}&apos; contains the trait &apos;{2}&apos;, so it should not be in the collection &apos;{3}&apos;..
        /// </summary>
        internal static string ErrUnexpectedIncrementalPartitionTrait {
            get {
                return ResourceManager.GetString("ErrUnexpectedIncrementalPartitionTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type found. Expected type {0} {1}.
        /// </summary>
        internal static string ErrUnexpectedType {
            get {
                return ResourceManager.GetString("ErrUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has an unrecognized dataType..
        /// </summary>
        internal static string ErrUnrecognizedDataType {
            get {
                return ResourceManager.GetString("ErrUnrecognizedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized type.
        /// </summary>
        internal static string ErrUnrecognizedType {
            get {
                return ResourceManager.GetString("ErrUnrecognizedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute references are not supported. Fix {0} {1}.
        /// </summary>
        internal static string ErrUnsupportedRef {
            get {
                return ResourceManager.GetString("ErrUnsupportedRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value type not supported. Please use JArray..
        /// </summary>
        internal static string ErrUnsupportedType {
            get {
                return ResourceManager.GetString("ErrUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity check failed. The object &apos;{0}&apos; is missing the following fields: {1}.
        /// </summary>
        internal static string ErrValdnIntegrityCheckFailure {
            get {
                return ResourceManager.GetString("ErrValdnIntegrityCheckFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid corpus path {0}.
        /// </summary>
        internal static string ErrValdnInvalidCorpusPath {
            get {
                return ResourceManager.GetString("ErrValdnInvalidCorpusPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested path &apos;{0}&apos; refers a document that failed validation..
        /// </summary>
        internal static string ErrValdnInvalidDoc {
            get {
                return ResourceManager.GetString("ErrValdnInvalidDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &apos;{1}&apos; could not form a valid regular expression. Reason: {2}.
        /// </summary>
        internal static string ErrValdnInvalidExpression {
            get {
                return ResourceManager.GetString("ErrValdnInvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum cardinality {0}. Value must be greater than or equal to 0 and less than maxCardinality..
        /// </summary>
        internal static string ErrValdnInvalidMaxCardinality {
            get {
                return ResourceManager.GetString("ErrValdnInvalidMaxCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum cardinality {0}. Value must be a number greater than zero or &apos;*&apos;..
        /// </summary>
        internal static string ErrValdnInvalidMinCardinality {
            get {
                return ResourceManager.GetString("ErrValdnInvalidMinCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document object &apos;{0}&apos; has not been added to any folder object..
        /// </summary>
        internal static string ErrValdnMissingDoc {
            get {
                return ResourceManager.GetString("ErrValdnMissingDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;defaultValue&apos; property is empty or one of its entries is missing &apos;languageTag&apos; and &apos;displayText&apos; values..
        /// </summary>
        internal static string ErrValdnMissingLanguageTag {
            get {
                return ResourceManager.GetString("ErrValdnMissingLanguageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported annotation type..
        /// </summary>
        internal static string WarnAnnotationTypeNotSupported {
            get {
                return ResourceManager.GetString("WarnAnnotationTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution guidance is being deprecated in favor of Projections. https://docs.microsoft.com/en-us/common-data-model/sdk/convert-logical-entities-resolved-entities#projection-overview..
        /// </summary>
        internal static string WarnDeprecatedResolutionGuidance {
            get {
                return ResourceManager.GetString("WarnDeprecatedResolutionGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discarding changes in document: {0}.
        /// </summary>
        internal static string WarnDocChangesDiscarded {
            get {
                return ResourceManager.GetString("WarnDocChangesDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import document {0} not loaded. This may cause unexpected behavior of the model..
        /// </summary>
        internal static string WarnDocImportNotLoaded {
            get {
                return ResourceManager.GetString("WarnDocImportNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait &apos;is.linkedEntity.identifier&apos; is not accepting arguments, skipping relationship recording for attribute &apos;{0}&apos; in entity &apos;{1}&apos;..
        /// </summary>
        internal static string WarnLinkEntIdentArgsNotSupported {
            get {
                return ResourceManager.GetString("WarnLinkEntIdentArgsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity max depth of {0} has been exceeded. Entity {1} will not be resolved any further..
        /// </summary>
        internal static string WarnMaxDepthExceeded {
            get {
                return ResourceManager.GetString("WarnMaxDepthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch all files in the folder location &apos;{0}&apos; described by a partition pattern. Exception: {1}.
        /// </summary>
        internal static string WarnPartitionFileFetchFailed {
            get {
                return ResourceManager.GetString("WarnPartitionFileFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Partition Pattern contains both a glob pattern ({0}) and a regular expression ({1}) set, the glob pattern will be used..
        /// </summary>
        internal static string WarnPartitionGlobAndRegexPresent {
            get {
                return ResourceManager.GetString("WarnPartitionGlobAndRegexPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid set of arguments provided for data partition corresponding to location: {0}.
        /// </summary>
        internal static string WarnPartitionInvalidArguments {
            get {
                return ResourceManager.GetString("WarnPartitionInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom extensions are not supported in referenced entity &apos;{0}&apos;..
        /// </summary>
        internal static string WarnPersistCustomExtNotSupported {
            get {
                return ResourceManager.GetString("WarnPersistCustomExtNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} is not inside a document or its owner is not a document..
        /// </summary>
        internal static string WarnPersistEntityMissing {
            get {
                return ResourceManager.GetString("WarnPersistEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an enum value for {0}..
        /// </summary>
        internal static string WarnPersistEnumNotFound {
            get {
                return ResourceManager.GetString("WarnPersistEnumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute file last modified time. Reason &apos;{0}&apos;.
        /// </summary>
        internal static string WarnPersistFileModTimeFailure {
            get {
                return ResourceManager.GetString("WarnPersistFileModTimeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read &apos;{0}&apos; from the &apos;{1}&apos; namespace. Reason &apos;{2}&apos;.
        /// </summary>
        internal static string WarnPersistFileReadFailure {
            get {
                return ResourceManager.GetString("WarnPersistFileReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jsonSemanticVersion must be set using the format &lt;major&gt;.&lt;minor&gt;.&lt;patch&gt;..
        /// </summary>
        internal static string WarnPersistJsonSemVerInvalidFormat {
            get {
                return ResourceManager.GetString("WarnPersistJsonSemVerInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jsonSemanticVersion is a required property of a document..
        /// </summary>
        internal static string WarnPersistJsonSemVerMandatory {
            get {
                return ResourceManager.GetString("WarnPersistJsonSemVerMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue while trying to read relationships from the model.json file..
        /// </summary>
        internal static string WarnPersistModelJsonRelReadFailed {
            get {
                return ResourceManager.GetString("WarnPersistModelJsonRelReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find data partition&apos;s location for partition {0}..
        /// </summary>
        internal static string WarnPersistPartitionLocMissing {
            get {
                return ResourceManager.GetString("WarnPersistPartitionLocMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data partition name must be set when exporting to model.json. Defaulting to empty string..
        /// </summary>
        internal static string WarnPersistPartitionNameNull {
            get {
                return ResourceManager.GetString("WarnPersistPartitionNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship&apos;s source entity &apos;{0}&apos; is not defined..
        /// </summary>
        internal static string WarnPersistRelUndefinedSourceEntity {
            get {
                return ResourceManager.GetString("WarnPersistRelUndefinedSourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship&apos;s target entity &apos;{0}&apos; is not defined..
        /// </summary>
        internal static string WarnPersistRelUndefinedTargetEntity {
            get {
                return ResourceManager.GetString("WarnPersistRelUndefinedTargetEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDM manifest with path {0} does not contain any entity so empty database created..
        /// </summary>
        internal static string WarnPersistSymsDbCreatedWithoutTables {
            get {
                return ResourceManager.GetString("WarnPersistSymsDbCreatedWithoutTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} is not inside a document or its owner is not a document..
        /// </summary>
        internal static string WarnPersistSymsEntityMissing {
            get {
                return ResourceManager.GetString("WarnPersistSymsEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} has been skipped. This may occur if entity format type not supported..
        /// </summary>
        internal static string WarnPersistSymsEntitySkipped {
            get {
                return ResourceManager.GetString("WarnPersistSymsEntitySkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection exist only for logical entities..
        /// </summary>
        internal static string WarnPersistSymsProjNotExist {
            get {
                return ResourceManager.GetString("WarnPersistSymsProjNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ObjectModel version supports json semantic version {0} at maximum. Trying to load a document with version {1}..
        /// </summary>
        internal static string WarnPersistUnsupportedJsonSemVer {
            get {
                return ResourceManager.GetString("WarnPersistUnsupportedJsonSemVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation AddArtifactAttribute is not supported on {0} yet..
        /// </summary>
        internal static string WarnProjAddArtifactAttrNotSupported {
            get {
                return ResourceManager.GetString("WarnProjAddArtifactAttrNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an attribute without owner while creating relationship traits for attribute {0}..
        /// </summary>
        internal static string WarnProjCreateForeignKeyTraits {
            get {
                return ResourceManager.GetString("WarnProjCreateForeignKeyTraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found ReplaceAsForeignKey operation for attribute &apos;{0}&apos; without a source entity. This operation is only supported on an entity typed attribute..
        /// </summary>
        internal static string WarnProjFKWithoutSourceEntity {
            get {
                return ResourceManager.GetString("WarnProjFKWithoutSourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation RenameAttributes is not supported on an attribute group yet..
        /// </summary>
        internal static string WarnProjRenameAttrNotSupported {
            get {
                return ResourceManager.GetString("WarnProjRenameAttrNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the attribute promise for &apos;{0}&apos;.
        /// </summary>
        internal static string WarnResolveAttrFailed {
            get {
                return ResourceManager.GetString("WarnResolveAttrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to resolve an entity named &apos;{0}&apos; from the reference &apos;{1}.
        /// </summary>
        internal static string WarnResolveEntityFailed {
            get {
                return ResourceManager.GetString("WarnResolveEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve import for &apos;{0}&apos;.
        /// </summary>
        internal static string WarnResolveImportFailed {
            get {
                return ResourceManager.GetString("WarnResolveImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to resolve an object from the reference &apos;{0}&apos;.
        /// </summary>
        internal static string WarnResolveObjectFailed {
            get {
                return ResourceManager.GetString("WarnResolveObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve the reference &apos;{0}&apos; to a known object.
        /// </summary>
        internal static string WarnResolveReferenceFailure {
            get {
                return ResourceManager.GetString("WarnResolveReferenceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected path prefix to end in /, but it didn&apos;t. Appended the / {0}.
        /// </summary>
        internal static string WarnStorageExpectedPathPrefix {
            get {
                return ResourceManager.GetString("WarnStorageExpectedPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the adapter from a non-existing namespace &apos;{0}&apos;..
        /// </summary>
        internal static string WarnStorageRemoveAdapterFailed {
            get {
                return ResourceManager.GetString("WarnStorageRemoveAdapterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to ingest telemetry. Reason &apos;{0}&apos;.
        /// </summary>
        internal static string WarnTelemetryIngestionFailed {
            get {
                return ResourceManager.GetString("WarnTelemetryIngestionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmounting the cdm namespace in order to use offline mode has been deprecated. The default behavior will now be using the CdmStandards package instead of the online schema store. Please remove this Unmount API call..
        /// </summary>
        internal static string WarnUnmountCdmNamespace {
            get {
                return ResourceManager.GetString("WarnUnmountCdmNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constant entity &apos;{0}&apos; defined without a constant value..
        /// </summary>
        internal static string WarnValdnEntityNotDefined {
            get {
                return ResourceManager.GetString("WarnValdnEntityNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endOrdinal &apos;{0}&apos; is greater than the maximum allowed ordinal &apos;{1}.
        /// </summary>
        internal static string WarnValdnMaxOrdinalTooHigh {
            get {
                return ResourceManager.GetString("WarnValdnMaxOrdinalTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startOrdinal {0} should not be greater than endOrdinal {1}.
        /// </summary>
        internal static string WarnValdnOrdinalStartEndOrder {
            get {
                return ResourceManager.GetString("WarnValdnOrdinalStartEndOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key is missing for entity &apos;{0}&apos;..
        /// </summary>
        internal static string WarnValdnPrimaryKeyMissing {
            get {
                return ResourceManager.GetString("WarnValdnPrimaryKeyMissing", resourceCulture);
            }
        }
    }
}
