//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CdmFolders.ObjectModel.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelSamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CdmFolders.ObjectModel.Tests.ModelSamples", typeof(ModelSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;name&quot;: &quot;test_extended_model_92782337-43a2-4a97-ac03-244ce2daf6cc&quot;, &quot;xyz:extendedAttribute&quot;: &quot;CDEFG_ModelExtendedAttr&quot;, &quot;application&quot;: &quot;extendedModel&quot;, &quot;version&quot;: &quot;1.0&quot;, &quot;culture&quot;: &quot;es-ES&quot;, &quot;annotations&quot;: [ { &quot;name&quot;: &quot;DEFGH&quot;, &quot;value&quot;: &quot;FGHIJ&quot; }, { &quot;name&quot;: &quot;GHIJK&quot;, &quot;value&quot;: &quot;IJKLM&quot; }, { &quot;name&quot;: &quot;JKLMN&quot;, &quot;value&quot;: &quot;LMNOP&quot; }, { &quot;name&quot;: &quot;MNOPQ&quot;, &quot;value&quot;: &quot;OPQRS&quot; }, { &quot;name&quot;: &quot;PQRST&quot;, &quot;value&quot;: &quot;RSTUV&quot; } ], &quot;entities&quot;: [ { &quot;$type&quot;: &quot;LocalEntity&quot;, &quot;name&quot;: &quot;NOPQR&quot;, &quot;description&quot;: &quot;PQRST&quot;, &quot;isHidden&quot;: true, &quot;xyz:ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtendedModelJson {
            get {
                return ResourceManager.GetString("ExtendedModelJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;application&quot;: &quot;demoapp&quot;, &quot;name&quot;: &quot;modelName&quot;, &quot;version&quot;: &quot;1.0&quot;, &quot;annotations&quot;: [ { &quot;name&quot;: &quot;6LA2G7&quot;, &quot;value&quot;: &quot;F9YPTF&quot; } ], &quot;culture&quot;: &quot;fr-CA&quot;, &quot;entities&quot;: [ { &quot;$type&quot;: &quot;ReferenceEntity&quot;, &quot;name&quot;: &quot;DEEMVB&quot;, &quot;source&quot;: &quot;some&quot;, &quot;modelId&quot;: &quot;7&quot;, &quot;description&quot;: &quot;ZSGVDO&quot;, &quot;annotations&quot;: [ { &quot;name&quot;: &quot;T8XFT0&quot;, &quot;value&quot;: &quot;AXLH1Z&quot; } ], &quot;isHidden&quot;: true, &quot;attributes&quot;: [ { &quot;name&quot;: &quot;21RKOI&quot;, &quot;description&quot;: &quot;XIPT3H&quot;, &quot;annotations&quot;: [ { &quot;name&quot;: &quot;T7YEFT&quot;, &quot;value&quot;: &quot;P663TI&quot; }, { &quot;name&quot;: &quot;89E4KR&quot;, &quot;value&quot;: &quot;AH33Q4&quot; } ], &quot;isH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelJson {
            get {
                return ResourceManager.GetString("ModelJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;invalidVersionModel&quot;,&quot;version&quot;:&quot;999.0&quot;}.
        /// </summary>
        internal static string ModelJsonInvalidVersion {
            get {
                return ResourceManager.GetString("ModelJsonInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;no version model&quot;}.
        /// </summary>
        internal static string ModelJsonNoVersion {
            get {
                return ResourceManager.GetString("ModelJsonNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;My Sales Count (счет) Model&quot;,&quot;version&quot;:&quot;1.0&quot;}.
        /// </summary>
        internal static string ModelJsonWithUnicode {
            get {
                return ResourceManager.GetString("ModelJsonWithUnicode", resourceCulture);
            }
        }
    }
}
