// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Column information for relationship
    /// </summary>
    public partial class ColumnRelationshipInformation
    {
        /// <summary>
        /// Initializes a new instance of the ColumnRelationshipInformation
        /// class.
        /// </summary>
        public ColumnRelationshipInformation() { }

        /// <summary>
        /// Initializes a new instance of the ColumnRelationshipInformation
        /// class.
        /// </summary>
        /// <param name="fromColumnName">From Column Name</param>
        /// <param name="toColumnName">To Column Name</param>
        public ColumnRelationshipInformation(string fromColumnName, string toColumnName)
        {
            FromColumnName = fromColumnName;
            ToColumnName = toColumnName;
        }

        /// <summary>
        /// Gets or sets from Column Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FromColumnName")]
        public string FromColumnName { get; set; }

        /// <summary>
        /// Gets or sets to Column Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ToColumnName")]
        public string ToColumnName { get; set; }
    }
}
