// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Data source properties.
    /// </summary>
    public partial class DataSource
    {
        /// <summary>
        /// Initializes a new instance of the DataSource class.
        /// </summary>
        public DataSource() { }

        /// <summary>
        /// Initializes a new instance of the DataSource class.
        /// </summary>
        /// <param name="location">Data source location.</param>
        /// <param name="provider">Data source provider information.</param>
        /// <param name="properties">Property bag.</param>
        public DataSource(string location, string provider = default(string), System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>))
        {
            Provider = provider;
            Location = location;
            Properties = properties;
        }

        /// <summary>
        /// Gets or sets data source provider information.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Provider")]
        public string Provider { get; set; }

        /// <summary>
        /// Gets or sets data source location.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets property bag.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Properties")]
        public System.Collections.Generic.IDictionary<string, JToken> Properties { get; set; }

    }
}
