// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// DDL batch.
    /// </summary>
    public partial class DDLBatch
    {
        /// <summary>
        /// Initializes a new instance of the DDLBatch class.
        /// </summary>
        public DDLBatch() { }

        /// <summary>
        /// Initializes a new instance of the DDLBatch class.
        /// </summary>
        public DDLBatch(System.Collections.Generic.IList<DDLPayload> dDLs)
        {
            DDLs = dDLs;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DDLs")]
        public System.Collections.Generic.IList<DDLPayload> DDLs { get; set; }

    }
}
