// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Distribution information.
    /// </summary>
    public partial class DistributionInfo
    {
        /// <summary>
        /// Initializes a new instance of the DistributionInfo class.
        /// </summary>
        public DistributionInfo() { }

        /// <summary>
        /// Initializes a new instance of the DistributionInfo class.
        /// </summary>
        /// <param name="type">Distribution type.</param>
        /// <param name="keys">Distribution keys.</param>
        /// <param name="count">Distribution count.</param>
        /// <param name="sortKeys">Distribution sort keys.</param>
        public DistributionInfo(string type = default(string), System.Collections.Generic.IList<string> keys = default(System.Collections.Generic.IList<string>), int? count = default(int?), System.Collections.Generic.IList<Sorting> sortKeys = default(System.Collections.Generic.IList<Sorting>))
        {
            Type = type;
            Keys = keys;
            Count = count;
            SortKeys = sortKeys;
        }

        /// <summary>
        /// Gets or sets distribution type.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets distribution keys.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Keys")]
        public System.Collections.Generic.IList<string> Keys { get; set; }

        /// <summary>
        /// Gets or sets distribution count.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Count")]
        public int? Count { get; set; }

        /// <summary>
        /// Gets or sets distribution sort keys.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SortKeys")]
        public System.Collections.Generic.IList<Sorting> SortKeys { get; set; }

    }
}
