// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Format information.
    /// </summary>
    public partial class FormatInfo
    {
        /// <summary>
        /// Initializes a new instance of the FormatInfo class.
        /// </summary>
        public FormatInfo() { }

        /// <summary>
        /// Initializes a new instance of the FormatInfo class.
        /// </summary>
        /// <param name="inputFormat">Possible values include:
        /// 'org.apache.hadoop.mapred.SequenceFileInputFormat',
        /// 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'</param>
        /// <param name="outputFormat">Possible values include:
        /// 'org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat',
        /// 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'</param>
        /// <param name="formatType">Possible values include: 'csv',
        /// 'parquet'</param>
        /// <param name="serializeLib">Possible values include:
        /// 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe',
        /// 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'</param>
        /// <param name="properties">Property bag.</param>
        /// <param name="serDeName">SerDe name.</param>
        public FormatInfo(string inputFormat, string outputFormat, FormatType formatType, SerializeLib serializeLib, System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>), string serDeName = default(string))
        {
            InputFormat = inputFormat;
            OutputFormat = outputFormat;
            FormatType = formatType;
            Properties = properties;
            SerDeName = serDeName;
            SerializeLib = serializeLib;
        }

        /// <summary>
        /// Gets or sets possible values include:
        /// 'org.apache.hadoop.mapred.SequenceFileInputFormat',
        /// 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "InputFormat")]
        public string InputFormat { get; set; }

        /// <summary>
        /// Gets or sets possible values include:
        /// 'org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat',
        /// 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "OutputFormat")]
        public string OutputFormat { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'csv', 'parquet'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FormatType")]
        public FormatType FormatType { get; set; }

        /// <summary>
        /// Gets or sets property bag.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Properties")]
        public System.Collections.Generic.IDictionary<string, JToken> Properties { get; set; }

        /// <summary>
        /// Gets or sets serDe name.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SerDeName")]
        public string SerDeName { get; set; }

        /// <summary>
        /// Gets or sets possible values include:
        /// 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe',
        /// 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SerializeLib")]
        public SerializeLib SerializeLib { get; set; }
    }
}
