// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// MD Entity
    /// </summary>
    public partial class MDEntity
    {
        /// <summary>
        /// Initializes a new instance of the MDEntity class.
        /// </summary>
        public MDEntity() { }

        /// <summary>
        /// Initializes a new instance of the MDEntity class.
        /// </summary>
        /// <param name="name">Entity Name.</param>
        /// <param name="type">Possible values include: 'DATABASE', 'TABLE',
        /// 'SCHEMA', 'VIEW', 'FUNCTION', 'PARTITIONINFO',
        /// 'RELATIONSHIP'</param>
        /// <param name="id">Entity Resource Id.</param>
        public MDEntity(string name, SASEntityType type, string id = default(string), object properties = default(object))
        {
            Name = name;
            Type = type;
            Id = id;
            Properties = properties;
        }

        /// <summary>
        /// Gets or sets entity Name.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'DATABASE', 'TABLE',
        /// 'SCHEMA', 'VIEW', 'FUNCTION', 'PARTITIONINFO', 'RELATIONSHIP'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public SASEntityType Type { get; set; }

        /// <summary>
        /// Gets entity Resource Id.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public string Id { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties")]
        public object Properties { get; set; }
    }
}
