// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Defines the artifact entity.
    /// </summary>
    public partial class MDEntityProperties
    {
        /// <summary>
        /// Initializes a new instance of the MDEntityProperties class.
        /// </summary>
        public MDEntityProperties() { }

        /// <summary>
        /// Initializes a new instance of the MDEntityProperties class.
        /// </summary>
        /// <param name="originObjectId">Entity object id maintained by the
        /// caller.</param>
        /// <param name="objectId">Entity object id maintained by SyMS.</param>
        /// <param name="objectVersion">Entity object version maintained by
        /// SyMS.</param>
        /// <param name="publishStatus">Possible values include:
        /// 'PUBLISHED'</param>
        /// <param name="properties">Property bag</param>
        public MDEntityProperties(string originObjectId = default(string), string objectId = default(string), long? objectVersion = default(long?), PublishStatus? publishStatus = default(PublishStatus?), System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>))
        {
            OriginObjectId = originObjectId;
            ObjectId = objectId;
            ObjectVersion = objectVersion;
            PublishStatus = publishStatus;
            Properties = properties;
        }

        /// <summary>
        /// Gets or sets entity object id maintained by the caller.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "OriginObjectId")]
        public string OriginObjectId { get; set; }

        /// <summary>
        /// Gets entity object id maintained by SyMS.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ObjectId")]
        public string ObjectId { get; private set; }

        /// <summary>
        /// Gets entity object version maintained by SyMS.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ObjectVersion")]
        public long? ObjectVersion { get; private set; }

        /// <summary>
        /// Gets or sets possible values include: 'PUBLISHED'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PublishStatus")]
        public PublishStatus? PublishStatus { get; set; }

        /// <summary>
        /// Gets or sets property bag
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Properties")]
        public System.Collections.Generic.IDictionary<string, JToken> Properties { get; set; }

    }
}
