// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Namespace.
    /// </summary>
    public partial class NamespaceModel
    {
        /// <summary>
        /// Initializes a new instance of the NamespaceModel class.
        /// </summary>
        public NamespaceModel() { }

        /// <summary>
        /// Initializes a new instance of the NamespaceModel class.
        /// </summary>
        /// <param name="databaseName">Database name.</param>
        public NamespaceModel(string databaseName)
        {
            DatabaseName = databaseName;
        }

        /// <summary>
        /// Gets or sets database name.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DatabaseName")]
        public string DatabaseName { get; set; }
    }
}
