// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{

    /// <summary>
    /// Defines values for OutputFormat.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum OutputFormat
    {
        [System.Runtime.Serialization.EnumMember(Value = "org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat")]
        OrgapachehadoophiveqlioHiveSequenceFileOutputFormat,
        [System.Runtime.Serialization.EnumMember(Value = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat")]
        OrgapachehadoophiveqlioparquetMapredParquetOutputFormat,
        [System.Runtime.Serialization.EnumMember(Value = "org.apache.hadoop.mapred.TextOutputFormat")]
        OrgapachehadoopmapredTextOutputFormat
    }
}
