// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Partition information namespace.
    /// </summary>
    public partial class PartitionInfoNamespace : TableNamespace
    {
        /// <summary>
        /// Initializes a new instance of the PartitionInfoNamespace class.
        /// </summary>
        public PartitionInfoNamespace() { }

        /// <summary>
        /// Initializes a new instance of the PartitionInfoNamespace class.
        /// </summary>
        /// <param name="databaseName">Database name.</param>
        /// <param name="tableName">Table name.</param>
        /// <param name="schemaName">Schema name.</param>
        public PartitionInfoNamespace(string databaseName, string tableName, string schemaName = default(string))
            : base(databaseName, schemaName)
        {
            TableName = tableName;
        }

        /// <summary>
        /// Gets or sets table name.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "TableName")]
        public string TableName { get; set; }

    }
}
