// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{

    /// <summary>
    /// Defines values for RelationshipType.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum RelationshipType
    {
        [System.Runtime.Serialization.EnumMember(Value = "ONETOONE")]
        ONETOONE,
        [System.Runtime.Serialization.EnumMember(Value = "ONETOMANY")]
        ONETOMANY,
        [System.Runtime.Serialization.EnumMember(Value = "MANYTOONE")]
        MANYTOONE,
        [System.Runtime.Serialization.EnumMember(Value = "MANYTOMANY")]
        MANYTOMANY
    }
}
