// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{

    /// <summary>
    /// Defines values for SASEntityType.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SASEntityType
    {
        [System.Runtime.Serialization.EnumMember(Value = "DATABASE")]
        DATABASE,
        [System.Runtime.Serialization.EnumMember(Value = "TABLE")]
        TABLE,
        [System.Runtime.Serialization.EnumMember(Value = "SCHEMA")]
        SCHEMA,
        [System.Runtime.Serialization.EnumMember(Value = "VIEW")]
        VIEW,
        [System.Runtime.Serialization.EnumMember(Value = "FUNCTION")]
        FUNCTION,
        [System.Runtime.Serialization.EnumMember(Value = "PARTITIONINFO")]
        PARTITIONINFO,
        [System.Runtime.Serialization.EnumMember(Value = "RELATIONSHIP")]
        RELATIONSHIP
    }
}
