// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Scalar type information
    /// </summary>
    public partial class ScalarTypeInfo : TypeInfo
    {
        /// <summary>
        /// Initializes a new instance of the ScalarTypeInfo class.
        /// </summary>
        public ScalarTypeInfo() { }

        /// <summary>
        /// Initializes a new instance of the ScalarTypeInfo class.
        /// </summary>
        /// <param name="typeName">Type name.</param>
        /// <param name="typeFamily">Type family.</param>
        /// <param name="isTableType">Is Table type.</param>
        /// <param name="isComplexType">Is Complex type.</param>
        /// <param name="isNullable">Is Nullable.</param>
        /// <param name="length">Length.</param>
        /// <param name="precision">Precision.</param>
        /// <param name="scale">Scale.</param>
        /// <param name="properties">Property bag.</param>
        public ScalarTypeInfo(string typeName, string typeFamily = default(string), bool? isTableType = default(bool?), bool? isComplexType = default(bool?), bool? isNullable = default(bool?), int? length = default(int?), int? precision = default(int?), int? scale = default(int?), System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>))
            : base(typeName, typeFamily, isTableType, isComplexType, isNullable, length, precision, scale, properties)
        {
        }
    }
}
