// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Database properties.
    /// </summary>
    public partial class SchemaProperties : MDEntityProperties
    {
        /// <summary>
        /// Initializes a new instance of the SchemaProperties class.
        /// </summary>
        public SchemaProperties() { }

        /// <summary>
        /// Initializes a new instance of the SchemaProperties class.
        /// </summary>
        /// <param name="originObjectId">Entity object id maintained by the
        /// caller.</param>
        /// <param name="objectId">Entity object id maintained by SyMS.</param>
        /// <param name="objectVersion">Entity object version maintained by
        /// SyMS.</param>
        /// <param name="publishStatus">Possible values include:
        /// 'PUBLISHED'</param>
        /// <param name="properties">Property bag</param>
        public SchemaProperties(NamespaceModel namespaceProperty, string originObjectId = default(string), string objectId = default(string), long? objectVersion = default(long?), PublishStatus? publishStatus = default(PublishStatus?), System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>))
            : base(originObjectId, objectId, objectVersion, publishStatus, properties)
        {
            NamespaceProperty = namespaceProperty;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Namespace")]
        public NamespaceModel NamespaceProperty { get; set; }

    }
}
