// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Column sorting.
    /// </summary>
    public partial class Sorting
    {
        /// <summary>
        /// Initializes a new instance of the Sorting class.
        /// </summary>
        public Sorting() { }

        /// <summary>
        /// Initializes a new instance of the Sorting class.
        /// </summary>
        /// <param name="keyName">Name of column.</param>
        /// <param name="sortOrder">Possible values include: 'DESC',
        /// 'ASC'</param>
        public Sorting(string keyName, SortOrder sortOrder)
        {
            KeyName = keyName;
            SortOrder = sortOrder;
        }

        /// <summary>
        /// Gets or sets name of column.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "KeyName")]
        public string KeyName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'DESC', 'ASC'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SortOrder")]
        public SortOrder SortOrder { get; set; }

    }
}
