// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{

    /// <summary>
    /// Defines values for SortOrder.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SortOrder
    {
        [System.Runtime.Serialization.EnumMember(Value = "DESC")]
        DESC,
        [System.Runtime.Serialization.EnumMember(Value = "ASC")]
        ASC
    }
}
