// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Storage descriptor
    /// </summary>
    public partial class StorageDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the StorageDescriptor class.
        /// </summary>
        public StorageDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the StorageDescriptor class.
        /// </summary>
        /// <param name="columns">Column information.</param>
        /// <param name="format">Storage descriptor format information.</param>
        /// <param name="source">Storage descriptor data source
        /// information.</param>
        /// <param name="distribution">Storage descriptor information.</param>
        /// <param name="properties">Property bag.</param>
        /// <param name="serDeInfo">SerDe information.</param>
        public StorageDescriptor(System.Collections.Generic.IList<DataColumn> columns, FormatInfo format, DataSource source, DistributionInfo distribution = default(DistributionInfo), System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>), object serDeInfo = default(object))
        {
            Distribution = distribution;
            Columns = columns;
            Format = format;
            Source = source;
            Properties = properties;
            SerDeInfo = serDeInfo;
        }

        /// <summary>
        /// Gets or sets storage descriptor information.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Distribution")]
        public DistributionInfo Distribution { get; set; }

        /// <summary>
        /// Gets or sets column information.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Columns")]
        public System.Collections.Generic.IList<DataColumn> Columns { get; set; }

        /// <summary>
        /// Gets or sets storage descriptor format information.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Format")]
        public FormatInfo Format { get; set; }

        /// <summary>
        /// Gets or sets storage descriptor data source information.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Source")]
        public DataSource Source { get; set; }

        /// <summary>
        /// Gets or sets property bag.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Properties")]
        public System.Collections.Generic.IDictionary<string, JToken> Properties { get; set; }

        /// <summary>
        /// Gets or sets serDe information.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SerDeInfo")]
        public object SerDeInfo { get; set; }

    }
}
