// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Defines the publish response.
    /// </summary>
    public partial class SyMSAPIDDLResponses
    {
        /// <summary>
        /// Initializes a new instance of the SyMSAPIDDLResponses class.
        /// </summary>
        public SyMSAPIDDLResponses() { }

        /// <summary>
        /// Initializes a new instance of the SyMSAPIDDLResponses class.
        /// </summary>
        /// <param name="syMSAPIDDLResponse">List of DDL response.</param>
        public SyMSAPIDDLResponses(System.Collections.Generic.IList<SyMSAPIDDLResponse> syMSAPIDDLResponse)
        {
            SyMSAPIDDLResponse = syMSAPIDDLResponse;
        }

        /// <summary>
        /// Gets or sets list of DDL response.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SyMSAPIDDLResponse")]
        public System.Collections.Generic.IList<SyMSAPIDDLResponse> SyMSAPIDDLResponse { get; set; }

    }
}
