// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Defines the response for create/publish operation on DDL payload.
    /// </summary>
    public partial class SyMSAPIDDLResponse
    {
        /// <summary>
        /// Initializes a new instance of the SyMSAPIDDLResponse class.
        /// </summary>
        public SyMSAPIDDLResponse() { }

        /// <summary>
        /// Initializes a new instance of the SyMSAPIDDLResponse class.
        /// </summary>
        /// <param name="dDLType">Possible values include: 'CREATE', 'ALTER',
        /// 'DROP'</param>
        /// <param name="entityName">Entity name.</param>
        /// <param name="entityType">Possible values include: 'DATABASE',
        /// 'TABLE', 'SCHEMA', 'VIEW', 'FUNCTION', 'PARTITIONINFO',
        /// 'RELATIONSHIP'</param>
        /// <param name="originObjectId">Object id maintained by Origin
        /// Catalog.</param>
        /// <param name="objectId">Object id maintained by SyMS.</param>
        /// <param name="objectVersion">Object version maintained by
        /// SyMS.</param>
        public SyMSAPIDDLResponse(DDLType dDLType, string entityName, SASEntityType entityType, string originObjectId, string objectId, long objectVersion)
        {
            DDLType = dDLType;
            EntityName = entityName;
            EntityType = entityType;
            OriginObjectId = originObjectId;
            ObjectId = objectId;
            ObjectVersion = objectVersion;
        }
        /// <summary>
        /// Static constructor for SyMSAPIDDLResponse class.
        /// </summary>
        static SyMSAPIDDLResponse()
        {
            PublishStatus = "PUBLISHED";
        }

        /// <summary>
        /// Gets or sets possible values include: 'CREATE', 'ALTER', 'DROP'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DDLType")]
        public DDLType DDLType { get; set; }

        /// <summary>
        /// Gets or sets entity name.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "EntityName")]
        public string EntityName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'DATABASE', 'TABLE',
        /// 'SCHEMA', 'VIEW', 'FUNCTION', 'PARTITIONINFO', 'RELATIONSHIP'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "EntityType")]
        public SASEntityType EntityType { get; set; }

        /// <summary>
        /// Gets or sets object id maintained by Origin Catalog.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "OriginObjectId")]
        public string OriginObjectId { get; set; }

        /// <summary>
        /// Gets or sets object id maintained by SyMS.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ObjectId")]
        public string ObjectId { get; set; }

        /// <summary>
        /// Gets or sets object version maintained by SyMS.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ObjectVersion")]
        public long ObjectVersion { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PublishStatus")]
        public static string PublishStatus { get; private set; }

    }
}
