// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Table partitioning information.
    /// </summary>
    public partial class TablePartitioning
    {
        /// <summary>
        /// Initializes a new instance of the TablePartitioning class.
        /// </summary>
        public TablePartitioning() { }

        /// <summary>
        /// Initializes a new instance of the TablePartitioning class.
        /// </summary>
        /// <param name="keys">Table partitioning keys.</param>
        public TablePartitioning(System.Collections.Generic.IList<string> keys)
        {
            Keys = keys;
        }
        /// <summary>
        /// Static constructor for TablePartitioning class.
        /// </summary>
        static TablePartitioning()
        {
            PartitionFunctionType = "value";
        }

        /// <summary>
        /// Gets or sets table partitioning keys.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Keys")]
        public System.Collections.Generic.IList<string> Keys { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PartitionFunctionType")]
        public static string PartitionFunctionType { get; private set; }

    }
}
