// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{

    /// <summary>
    /// Defines values for TableType.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum TableType
    {
        [System.Runtime.Serialization.EnumMember(Value = "MANAGED")]
        MANAGED,
        [System.Runtime.Serialization.EnumMember(Value = "EXTERNAL")]
        EXTERNAL
    }
}
