// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Table namespace.
    /// </summary>
    public partial class TableNamespace : NamespaceModel
    {
        /// <summary>
        /// Initializes a new instance of the TableNamespace class.
        /// </summary>
        public TableNamespace() { }

        /// <summary>
        /// Initializes a new instance of the TableNamespace class.
        /// </summary>
        /// <param name="databaseName">Database name.</param>
        /// <param name="schemaName">Schema name.</param>
        public TableNamespace(string databaseName, string schemaName = default(string))
            : base(databaseName)
        {
            SchemaName = schemaName;
        }

        /// <summary>
        /// Gets or sets schema name.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SchemaName")]
        public string SchemaName { get; set; }
    }
}
