// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{

    /// <summary>
    /// Defines values for ValidationType.
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum ValidationType
    {
        [System.Runtime.Serialization.EnumMember(Value = "IDWValidation")]
        IDWValidation
    }
}
