// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// Database properties.
    /// </summary>
    public partial class ViewEntityProperties : MDEntityProperties
    {
        /// <summary>
        /// Initializes a new instance of the ViewEntityProperties class.
        /// </summary>
        public ViewEntityProperties()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ViewEntityProperties class.
        /// </summary>
        /// <param name="originObjectId">Entity object id maintained by the
        /// caller.</param>
        /// <param name="objectId">Entity object id maintained by SyMS.</param>
        /// <param name="objectVersion">Entity object version maintained by
        /// SyMS.</param>
        /// <param name="publishStatus">Possible values include:
        /// 'PUBLISHED'</param>
        /// <param name="properties">Property bag</param>
        /// <param name="viewOriginalText">View original text.</param>
        /// <param name="viewExpandedText">View expanded text.</param>
        /// <param name="temporary">Temporary.</param>
        /// <param name="isRewriteEnabled">Is rewrite enabled.</param>
        public ViewEntityProperties(TableNamespace namespaceProperty, StorageDescriptor storageDescriptor, string originObjectId = default(string), string objectId = default(string), long? objectVersion = default(long?), PublishStatus? publishStatus = default(PublishStatus?), System.Collections.Generic.IDictionary<string, JToken> properties = default(System.Collections.Generic.IDictionary<string, JToken>), TablePartitioning partitioning = default(TablePartitioning), string viewOriginalText = default(string), string viewExpandedText = default(string), bool? temporary = default(bool?), bool? isRewriteEnabled = default(bool?))
            : base(originObjectId, objectId, objectVersion, publishStatus, properties)
        {
            NamespaceProperty = namespaceProperty;
            Partitioning = partitioning;
            StorageDescriptor = storageDescriptor;
            ViewOriginalText = viewOriginalText;
            ViewExpandedText = viewExpandedText;
            Temporary = temporary;
            IsRewriteEnabled = isRewriteEnabled;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Namespace")]
        public TableNamespace NamespaceProperty { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Partitioning")]
        public TablePartitioning Partitioning { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "StorageDescriptor")]
        public StorageDescriptor StorageDescriptor { get; set; }

        /// <summary>
        /// Gets or sets view original text.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ViewOriginalText")]
        public string ViewOriginalText { get; set; }

        /// <summary>
        /// Gets or sets view expanded text.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ViewExpandedText")]
        public string ViewExpandedText { get; set; }

        /// <summary>
        /// Gets or sets temporary.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Temporary")]
        public bool? Temporary { get; set; }

        /// <summary>
        /// Gets or sets is rewrite enabled.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IsRewriteEnabled")]
        public bool? IsRewriteEnabled { get; set; }
    }
}
