// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.CommonDataModel.ObjectModel.Persistence.Syms.Models
{
    using Newtonsoft.Json.Linq;

    /// <summary>
    /// View entity
    /// </summary>
    public partial class ViewEntity : MDEntity
    {
        /// <summary>
        /// Initializes a new instance of the ViewEntity class.
        /// </summary>
        public ViewEntity() { }

        /// <summary>
        /// Initializes a new instance of the ViewEntity class.
        /// </summary>
        /// <param name="name">Entity Name.</param>
        /// <param name="type">Possible values include: 'DATABASE', 'TABLE',
        /// 'SCHEMA', 'VIEW', 'FUNCTION', 'PARTITIONINFO',
        /// 'RELATIONSHIP'</param>
        /// <param name="id">Entity Resource Id.</param>
        public ViewEntity(string name, SASEntityType type, string id = default(string), object properties = default(object))
            : base(name, type, id, properties)
        {
        }
    }
}
